import {
	Activity,
	AlertTriangle,
	AppWindow,
	ArrowRightLeft,
	BadgeCheck,
	Bell,
	BookOpen,
	Box,
	Briefcase,
	Building2,
	Calendar,
	CalendarClock,
	Car,
	ChartLine,
	CheckSquare,
	ChevronsDownUp,
	CircleDollarSign,
	CircleDot,
	Clock,
	Code,
	Columns2,
	Columns3,
	Contact,
	CreditCard,
	Database,
	Divide,
	FileBarChart,
	FileText,
	Fingerprint,
	FolderOpen,
	Fuel,
	Gauge,
	Globe,
	Hash,
	Heading1,
	Heading2,
	Image,
	Info,
	Key,
	LayoutDashboard,
	LayoutTemplate,
	Link2,
	List,
	ListFilter,
	ListTodo,
	Lock,
	Mail,
	MapPin,
	MessagesSquare,
	Minus,
	MousePointerClick,
	MoveVertical,
	Package,
	PackageX,
	PanelLeft,
	Paperclip,
	PieChart,
	Route,
	Rows3,
	ScrollText,
	Settings,
	Shield,
	ShoppingCart,
	Siren,
	SquareStack,
	Table2,
	Tag,
	Tags,
	Truck,
	Type,
	Users,
	Wrench,
	type LucideProps,
} from 'lucide-react';
import type { FC } from 'react';

/**
 * Single source of truth for every icon name the Studio renders by name — app
 * icons, menu icons, and the DB-driven catalog/block icons (design_components,
 * view_modes). Components render at whatever size the caller asks for, so this
 * one registry serves both `AppIcon`/`MenuIcon` and `dsIcon()`.
 */
export const APP_ICONS: Record<string, FC<LucideProps>> = {
	// App / menu icons (stored on the module as "lucide:<name>").
	box: Box,
	'layout-dashboard': LayoutDashboard,
	settings: Settings,
	users: Users,
	'building-2': Building2,
	calendar: Calendar,
	'messages-square': MessagesSquare,
	'file-text': FileText,
	'pie-chart': PieChart,
	'book-open': BookOpen,
	briefcase: Briefcase,
	'shopping-cart': ShoppingCart,
	package: Package,
	truck: Truck,
	'dollar-sign': CreditCard,
	'bar-chart-3': Activity,
	bell: Bell,
	globe: Globe,
	'folder-open': FolderOpen,
	key: Key,
	link: Link2,
	'link-2': Link2,
	// Collection/menu icons — mirror the Mini App's per-module glyphs
	// (the client app launcher config).
	fingerprint: Fingerprint,
	'list-todo': ListTodo,
	car: Car,
	'scroll-text': ScrollText,
	shield: Shield,
	'circle-dot': CircleDot,
	wrench: Wrench,
	siren: Siren,
	fuel: Fuel,
	'package-x': PackageX,
	route: Route,
	'alert-triangle': AlertTriangle,
	'map-pin': MapPin,
	'arrow-right-left': ArrowRightLeft,

	// Catalog / block icons (design_components, view_modes).
	type: Type,
	'align-left': Box,
	code: Code,
	hash: Hash,
	divide: Divide,
	'circle-dollar-sign': CircleDollarSign,
	'check-square': CheckSquare,
	'list-filter': ListFilter,
	tags: Tags,
	'calendar-clock': CalendarClock,
	clock: Clock,
	mail: Mail,
	lock: Lock,
	paperclip: Paperclip,
	'heading-1': Heading1,
	'layout-template': LayoutTemplate,
	'move-vertical': MoveVertical,
	minus: Minus,
	'mouse-pointer-click': MousePointerClick,
	tag: Tag,
	image: Image,
	list: List,
	gauge: Gauge,
	'table-2': Table2,
	'columns-2': Columns2,
	'rows-3': Rows3,
	'columns-3': Columns3,
	'square-stack': SquareStack,
	'chevrons-down-up': ChevronsDownUp,
	'app-window': AppWindow,
	'panel-left': PanelLeft,
	database: Database,
	'media-panel': Contact,
	'info-row': Info,
	'counter-chip': BadgeCheck,
	'heading-2': Heading2,
	'chart-line': ChartLine,
	'file-bar-chart': FileBarChart,
};

/** Selectable icons for the New App dialog. */
export const ICON_OPTIONS = Object.entries(APP_ICONS).map(([name, Icon]) => ({ name, Icon }));
