import { BLOCK_REGISTRY } from '@mmbix/ui-views';
import {
	ChevronsDownUp,
	AlertTriangle,
	Gauge,
	Heading1,
	Image as ImageIcon,
	LayoutTemplate,
	List as ListIcon,
	Minus,
	MousePointerClick,
	MoveVertical,
	Rows3,
	SquareStack,
	Table2,
	Tag,
	Type,
	Box,
	Columns3,
	Heading2,
	Link2,
	ChartLine,
	FileBarChart,
	LayoutGrid,
	UserRound,
	PackageOpen,
	CircleGauge,
	ListChecks,
	SquarePen,
	AlignLeft,
	ChevronsUpDown,
	Search,
	SquareCheck,
	ToggleRight,
	ToggleLeft,
	CircleDot,
	SlidersHorizontal,
	Star,
	CalendarDays,
	Palette,
	Tags,
	PanelRight,
	PanelRightOpen,
	MessagesSquare,
	Scan,
	MessageCircleQuestion,
	BellRing,
	House,
	ChevronsRight,
	FilePenLine,
	LoaderCircle,
	Keyboard,
	FrameIcon,
	RectangleHorizontal,
	TextCursorInput,
	Hash,
	MessageCircle,
	MessageSquare,
	Paperclip,
	GalleryHorizontalEnd,
	Command,
	ChevronDown,
	MousePointer2,
	Menu,
	Navigation,
	PanelsLeftRight,
	ScrollText,
	FormInput,
	AppWindow,
	PanelLeft,
	Database,
	MapPin,
	ListFilter,
	Globe,
	Contact,
	Info,
	BadgeCheck,
} from 'lucide-react';
import type { PageBlock } from '../lib/api';

export interface BlockDef {
	type: string;
	label: string;
	icon: React.ReactNode;
	group: string;
	defaults: Record<string, unknown>;
}

/** Palette icons are app-local (lucide) — labels/groups/defaults come from the shared registry. */
const ICONS: Record<string, React.ReactNode> = {
	row: <Rows3 size={14} />,
	column: <Columns3 size={14} />,
	grid: <LayoutGrid size={14} />,
	tabs: <SquareStack size={14} />,
	accordion: <ChevronsDownUp size={14} />,
	card: <LayoutTemplate size={14} />,
	spacer: <MoveVertical size={14} />,
	divider: <Minus size={14} />,
	text: <Type size={14} />,
	heading: <Heading1 size={14} />,
	button: <MousePointerClick size={14} />,
	badge: <Tag size={14} />,
	alert: <AlertTriangle size={14} />,
	image: <ImageIcon size={14} />,
	list: <ListIcon size={14} />,
	kpi: <Gauge size={14} />,
	table: <Table2 size={14} />,
	'section-header': <Heading2 size={14} />,
	'links-card': <Link2 size={14} />,
	chart: <ChartLine size={14} />,
	report: <FileBarChart size={14} />,
	avatar: <UserRound size={14} />,
	skeleton: <Box size={14} />,
	empty: <PackageOpen size={14} />,
	progress: <CircleGauge size={14} />,
	'choice-card': <ListChecks size={14} />,
	input: <SquarePen size={14} />,
	textarea: <AlignLeft size={14} />,
	select: <ChevronsUpDown size={14} />,
	combobox: <Search size={14} />,
	checkbox: <SquareCheck size={14} />,
	switch: <ToggleRight size={14} />,
	toggle: <ToggleLeft size={14} />,
	'radio-group': <CircleDot size={14} />,
	slider: <SlidersHorizontal size={14} />,
	rating: <Star size={14} />,
	datepicker: <CalendarDays size={14} />,
	'color-picker': <Palette size={14} />,
	'search-box': <Search size={14} />,
	'tags-input': <Tags size={14} />,
	dialog: <SquareStack size={14} />,
	drawer: <PanelRight size={14} />,
	sheet: <PanelRightOpen size={14} />,
	popover: <MessagesSquare size={14} />,
	'hover-card': <Scan size={14} />,
	tooltip: <MessageCircleQuestion size={14} />,
	toast: <BellRing size={14} />,
	breadcrumb: <House size={14} />,
	pagination: <ChevronsRight size={14} />,
	'entity-card-grid': <LayoutGrid size={14} />,
	'entity-form': <FilePenLine size={14} />,
	kanban: <Columns3 size={14} />,
	calendar: <CalendarDays size={14} />,
	separator: <Minus size={14} />,
	spinner: <LoaderCircle size={14} />,
	kbd: <Keyboard size={14} />,
	'aspect-ratio': <FrameIcon size={14} />,
	'button-group': <RectangleHorizontal size={14} />,
	'input-group': <TextCursorInput size={14} />,
	field: <SquarePen size={14} />,
	'input-otp': <Hash size={14} />,
	'toggle-group': <ToggleRight size={14} />,
	frame: <FrameIcon size={14} />,
	item: <ListIcon size={14} />,
	bubble: <MessageCircle size={14} />,
	message: <MessageSquare size={14} />,
	attachment: <Paperclip size={14} />,
	collapsible: <ChevronsDownUp size={14} />,
	carousel: <GalleryHorizontalEnd size={14} />,
	command: <Command size={14} />,
	'message-scroller': <MessagesSquare size={14} />,
	'alert-dialog': <AlertTriangle size={14} />,
	'dropdown-menu': <ChevronDown size={14} />,
	'context-menu': <MousePointer2 size={14} />,
	menubar: <Menu size={14} />,
	'navigation-menu': <Navigation size={14} />,
	resizable: <PanelsLeftRight size={14} />,
	'scroll-area': <ScrollText size={14} />,
	form: <FormInput size={14} />,
	'module-grid': <LayoutGrid size={14} />,
	appshell: <AppWindow size={14} />,
	sidebar: <PanelLeft size={14} />,
	datatable: <Table2 size={14} />,
	schema: <Database size={14} />,
	marker: <MapPin size={14} />,
	'native-select': <ListFilter size={14} />,
	label: <Tag size={14} />,
	'locale-provider': <Globe size={14} />,
	'theme-provider': <Palette size={14} />,
	'media-panel': <Contact size={14} />,
	'info-row': <Info size={14} />,
	'counter-chip': <BadgeCheck size={14} />,
};

/** Page blocks the builder ships with — registry-driven so the palette and the
 *  runtime renderer always agree (single source of truth: @mmbix/ui-views). */
export const BLOCK_TYPES: BlockDef[] = BLOCK_REGISTRY.map((r) => ({
	...r,
	icon: ICONS[r.type] ?? <Box size={14} />,
}));

export function blankBlock(type: string): PageBlock {
	const def = BLOCK_REGISTRY.find((b) => b.type === type);
	return { id: crypto.randomUUID(), type, label: def?.label ?? type, layout: { order: 0 }, config: { ...(def?.defaults ?? {}) } };
}

/** View-config blocks are invisible layout metadata (per-view settings), not renderable blocks. */
export function isViewConfig(b: PageBlock): boolean {
	return b.type === '_view_config';
}
