#!/usr/bin/env node
/**
 * db:d1-export — generates the SQL seed for the PRODUCTION Studio metadata D1
 * (`mff-sys-studio-db`, binding STUDIO_DB on the studio worker) from the
 * committed local studio.db.
 *
 * Why not seed.sql: the dev pipeline (build.js) deliberately EXCLUDES
 * ds_exports (it is re-derived from the installed design system by
 * `pnpm db:sync-ds`) and keyboard_shortcuts — but the deployed worker cannot
 * run node/import the design system, so the prod seed must carry the full
 * 12-table snapshot the /__studio/meta route serves.
 *
 *   pnpm db:d1-export                         # writes studio.db/d1-seed.sql
 *   npx wrangler d1 execute mff-sys-studio-db --remote --file studio.db/d1-seed.sql
 *
 * The output file is git-ignored — it is a derived artifact of the committed
 * studio.db (regenerate + re-import whenever the local metadata is the source
 * of truth, same discipline as seed.sql).
 */
import { DatabaseSync } from 'node:sqlite';
import { writeFileSync, readFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const committed = join(here, 'studio.db');
const schemaPath = join(here, 'schema.sql');
const outPath = join(here, 'd1-seed.sql');

// FK-safe emit order (parents before children); every other table follows.
const ORDER = [
	'design_components',
	'component_props',
	'component_styles',
	'component_events',
	'view_modes',
	'page_templates',
	'template_views',
	'style_presets',
	'event_action_types',
	'ds_exports',
	'studio_config',
	'keyboard_shortcuts',
];

if (!existsSync(committed)) {
	console.error(`studio.db missing at ${committed} — run \`pnpm db:build\` first.`);
	process.exit(1);
}

const db = new DatabaseSync(committed, { readOnly: true });
const schema = readFileSync(schemaPath, 'utf8');

const esc = (v) => {
	if (v === null || v === undefined) return 'NULL';
	if (typeof v === 'number') return String(v);
	return `'${String(v).replace(/'/g, "''")}'`;
};

const tables = [
	...ORDER,
	...db
		.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name")
		.all()
		.map((r) => r.name)
		.filter((n) => !ORDER.includes(n)),
];

const lines = [
	'-- Auto-generated by studio.db/d1-export.js — do not edit by hand.',
	'-- Regenerate after Studio Admin edits: `pnpm db:d1-export`, then import into',
	'-- the prod Studio D1 with `wrangler d1 execute mff-sys-studio-db --remote --file`.',
	`-- Generated from ${committed} at ${new Date().toISOString()}`,
	'',
	schema.trim(),
	'',
];
for (const t of tables) {
	const cols = db
		.prepare(`PRAGMA table_info(${t})`)
		.all()
		.map((c) => c.name);
	const rows = db.prepare(`SELECT * FROM ${t} ORDER BY rowid`).all();
	lines.push(`-- ── ${t} (${rows.length} rows) ──`);
	if (rows.length > 0) {
		const colList = cols.map((c) => `"${c}"`).join(', ');
		for (const r of rows) {
			const vals = cols.map((c) => esc(r[c])).join(', ');
			lines.push(`INSERT INTO ${t} (${colList}) VALUES (${vals});`);
		}
	}
	lines.push('');
}

writeFileSync(outPath, lines.join('\n'));
db.close();
console.log(`d1-seed.sql regenerated from ${committed} → ${outPath}`);
console.log(`  ${tables.length} tables — import with:\n  npx wrangler d1 execute mff-sys-studio-db --remote --file ${outPath}`);
