#!/usr/bin/env node
/**
 * db:dump-seed — regenerates seed.sql from the CURRENT studio.db.
 *
 * Run after intentional Studio Admin edits so the seed (the committed source of
 * truth) reflects the working state:
 *   pnpm db:dump-seed && pnpm db:build && pnpm db:check
 *
 * ds_exports is excluded — it is derived from the installed design system
 * (regenerate with `pnpm db:sync-ds`), not from seed.
 */
import { DatabaseSync } from 'node:sqlite';
import { writeFileSync, readFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const committed = join(here, 'studio.db');
const seedPath = join(here, 'seed.sql');

// FK-safe emit order (parents before children), matching check.js + the plugin snapshot.
const ORDER = [
	'design_components', 'component_props', 'component_styles', 'component_events',
	'view_modes', 'page_templates', 'template_views', 'style_presets',
	'event_action_types', 'studio_config',
];
const EXCLUDE = new Set(['ds_exports', 'sqlite_sequence', ...ORDER]);

if (!existsSync(committed)) {
	console.error(`studio.db missing at ${committed} — run \`pnpm db:build\` first.`);
	process.exit(1);
}

const db = new DatabaseSync(committed, { readOnly: true });

const esc = (v) => {
	if (v === null || v === undefined) return 'NULL';
	if (typeof v === 'number') return String(v);
	return `'${String(v).replace(/'/g, "''")}'`;
};

const tables = [
	...ORDER,
	...db
		.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name")
		.all()
		.map((r) => r.name)
		.filter((n) => !EXCLUDE.has(n)),
];

const lines = [
	'-- Auto-generated by studio.db/dump-seed.js — do not edit by hand.',
	'-- Regenerate after Studio Admin edits: `pnpm db:dump-seed && pnpm db:build`',
	`-- Generated from ${committed} at ${new Date().toISOString()}`,
	'',
];
for (const t of tables) {
	const cols = db.prepare(`PRAGMA table_info(${t})`).all().map((c) => c.name);
	const rows = db.prepare(`SELECT * FROM ${t} ORDER BY rowid`).all();
	lines.push(`-- ── ${t} (${rows.length} rows) ──`);
	if (rows.length > 0) {
		const colList = cols.map((c) => `"${c}"`).join(', ');
		for (const r of rows) {
			const vals = cols.map((c) => esc(r[c])).join(', ');
			lines.push(`INSERT INTO ${t} (${colList}) VALUES (${vals});`);
		}
	}
	lines.push('');
}

writeFileSync(seedPath, lines.join('\n'));
db.close();
console.log(`seed.sql regenerated from ${committed} (${tables.length} tables)`);
