// NOTE: This file is auto-generated by scripts/exports.mjs.
// Run `pnpm generate:exports` after adding or removing a component.
// Heavy components (datatable, kanban, calendar, datepicker, command, carousel, scheduler, widgets, rich-text-editor) are exported via
// subpath imports only to keep the core bundle lean for edge runtimes.

// CSS — imported here so Vite bundles it into dist/index.css
import './index.css';

export { ThemeProvider, useTheme } from './components/theme-provider';
export { cn } from './lib/utils';
export { lockBodyScroll, unlockBodyScroll, useScrollLock } from './lib/hooks/use-scroll-lock';

export * from './components/accordion';
export * from './components/alert';
export * from './components/alert-dialog';
export * from './components/appshell';
export * from './components/aspect-ratio';
export * from './components/attachment';
export * from './components/avatar';
export * from './components/badge';
export * from './components/breadcrumb';
export * from './components/bubble';
export * from './components/button';
export * from './components/button-group';
export * from './components/card';
export * from './components/checkbox';
export * from './components/choice-card';
export * from './components/collapsible';
export * from './components/color-picker';
export * from './components/combobox';
export * from './components/context-menu';
export * from './components/counter-chip';
export * from './components/dialog';
export * from './components/drawer';
export * from './components/dropdown-menu';
export * from './components/empty';
export * from './components/field';
export * from './components/form';
export * from './components/frame';
export * from './components/hover-card';
export * from './components/info-row';
export * from './components/input';
export * from './components/input-group';
export * from './components/input-otp';
export * from './components/item';
export * from './components/kbd';
export * from './components/label';
export * from './components/links-card';
export * from './components/locale-provider';
export * from './components/media-panel';
export * from './components/menubar';
export * from './components/message';
export * from './components/message-scroller';
export * from './components/module-grid';
export * from './components/native-select';
export * from './components/navigation-menu';
export * from './components/pagination';
export * from './components/pivot';
export * from './components/popover';
export * from './components/progress';
export * from './components/radio-group';
export * from './components/rating';
export * from './components/resizable';
export * from './components/scroll-area';
export * from './components/search-box';
export * from './components/select';
export * from './components/separator';
export * from './components/sheet';
export * from './components/skeleton';
export * from './components/slider';
export * from './components/spinner';
export * from './components/switch';
export * from './components/table';
export * from './components/tabs';
export * from './components/tags-input';
export * from './components/textarea';
export * from './components/theme-provider';
export * from './components/timepicker';
export * from './components/toast';
export * from './components/toggle';
export * from './components/toggle-group';
export * from './components/tooltip';

// NOTE: Sidebar's exports are listed explicitly below so the canonical
// `SidebarHeader` (from ./sidebar) wins over appshell's same-named export.
export {
	Sidebar,
	SidebarContent,
	SidebarFooter,
	SidebarGroup,
	SidebarGroupAction,
	SidebarGroupContent,
	SidebarGroupLabel,
	SidebarHeader,
	SidebarInput,
	SidebarInset,
	SidebarMenu,
	SidebarMenuAction,
	SidebarMenuBadge,
	SidebarMenuButton,
	SidebarMenuItem,
	SidebarMenuSkeleton,
	SidebarMenuSub,
	SidebarMenuSubButton,
	SidebarMenuSubItem,
	SidebarProvider,
	SidebarRail,
	SidebarSeparator,
	SidebarTrigger,
	useSidebar,
} from './components/sidebar';
