// NOTE: This file is auto-generated by scripts/widgets.mjs.
// Run `node scripts/widgets.mjs` after adding or removing a widget file.
import type { WidgetDef } from "./types"
import { EmployeeCard, widgetMeta as employeeCardMeta } from "./employee-card"
import { SchedulerWidget, widgetMeta as schedulerMeta } from "./scheduler"

export const WIDGET_REGISTRY: WidgetDef[] = [
  employeeCardMeta,
  schedulerMeta,
]

export { EmployeeCard } from "./employee-card"
export { SchedulerWidget } from "./scheduler"

export function widgetDefOf(type: string): WidgetDef | undefined {
	return WIDGET_REGISTRY.find((w) => w.type === type)
}

/** Default config for a new widget block (spread into `config` on insert). */
export function widgetDefaults(def: WidgetDef): Record<string, unknown> {
	const out: Record<string, unknown> = { ...def.defaultProps }
	// Merge `props[*].default` values that defaultProps doesn't already set —
	// so a dropped widget gets its real field-mapping defaults (e.g.
	// employee-card nameField: 'full_name'), not an empty config.
	for (const [key, prop] of Object.entries(def.props)) {
		if (out[key] === undefined && prop.default !== undefined) out[key] = prop.default
	}
	return out
}

export type { WidgetDef, WidgetPropDef, WidgetPropType } from "./types"
