/**
 * TypeScript SDK Plugin
 *
 * Provides a typed API client for frontend/backend developers.
 * SDK methods are auto-generated from entity schemas.
 *
 * Usage:
 *   POST /api/sdk/generate → JSON with typed SDK code
 *   GET  /api/sdk/types    → TypeScript type definitions for all entities
 *
 * Bundle impact: ~1KB (metadata-only, no parser needed)
 */

import type { Plugin, PluginRegistration, PluginContext } from '@mmbix/types/worker';
import { Hono } from 'hono';
import { D1Client } from '@mmbix/core';
import type { EntitySchema, FieldDefinition } from '@mmbix/types';
import { requireAuth } from '@/routes/auth';
import { requireAdmin } from '@/middleware/rbac-guard';
import { findAllCollections } from '@/lib/services/schema-lookup';

const TS_TYPE_MAP: Record<string, string> = {
	text: 'string',
	integer: 'number',
	number: 'number',
	boolean: 'boolean',
	timestamp: 'string',
	json: 'Record<string, unknown>',
	slug: 'string',
	m2o: 'string',
	o2m: 'string[]',
	m2m: 'string[]',
	table: 'Record<string, unknown>[]',
	file: 'string',
	currency: 'number',
	percent: 'number',
	select: 'string',
	color: 'string',
	password: 'string',
	location: '{lat:number;lng:number;name?:string}',
	longtext: 'string',
	rating: 'number',
	bigint: 'number',
	csv: 'string[]',
	uuid: 'string',
	m2a: 'Record<string, {type:string;id:string}>',
	formula: 'unknown',
};

function generateTypes(collections: EntitySchema[]): string {
	const lines: string[] = [
		'// Auto-generated by Entity Engine SDK',
		'// Run: GET /api/sdk/types to regenerate',
		'',
		'export interface EntityEngineClient {',
		'  baseUrl: string;',
		'  token?: string;',
		'}',
		'',
	];

	for (const c of collections) {
		let fields: FieldDefinition[] = [];
		try {
			const p = JSON.parse(c.schema_json);
			if (p.fields) fields = p.fields;
		} catch {}

		const props = fields
			.filter((f) => f.name !== 'id')
			.map((f) => {
				let t: string;
				if (f.type === 'formula') {
					// Stored computed fields are real columns typed by result_type;
					// virtual formulas are computed on read (unknown on the wire).
					t =
						f.store === true
							? f.result_type === 'boolean'
								? 'boolean | number'
								: f.result_type === 'string' || f.result_type === 'json'
									? 'string'
									: 'number'
							: 'unknown';
				} else {
					t = TS_TYPE_MAP[f.type] || 'string';
				}
				return `  ${f.name}${f.required !== false ? '' : '?'}: ${t};`;
			});

		lines.push(`export interface ${c.name.replace(/\\s/g, '')} {`);
		lines.push('  id: string;');
		lines.push(...props);
		lines.push('  doc_status?: string;');
		lines.push('  created_at: string;');
		lines.push('  updated_at: string;');
		lines.push('}');
		lines.push('');

		lines.push(
			`export const ${c.slug}Api = {`,
			`  list: (params?: Record<string,string>) => fetch(\`\${baseUrl}/api/entities/${c.slug}?\${new URLSearchParams(params)}\`).then(r => r.json()),`,
			`  get: (id: string) => fetch(\`\${baseUrl}/api/entities/${c.slug}/\${id}\`).then(r => r.json()),`,
			`  create: (data: Partial<${c.name.replace(/\\s/g, '')}>) => fetch(\`\${baseUrl}/api/entities/${c.slug}\`, { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify(data) }).then(r => r.json()),`,
			`  update: (id: string, data: Partial<${c.name.replace(/\\s/g, '')}>) => fetch(\`\${baseUrl}/api/entities/${c.slug}/\${id}\`, { method:'PUT', headers:{'Content-Type':'application/json'}, body:JSON.stringify(data) }).then(r => r.json()),`,
			`  delete: (id: string) => fetch(\`\${baseUrl}/api/entities/${c.slug}/\${id}\`, { method:'DELETE' }).then(r => r.json()),`,
			`};`,
			'',
		);
	}

	return lines.join('\n');
}

export function sdkPlugin(): Plugin {
	return {
		id: 'sdk',
		name: 'TypeScript SDK Generator',
		version: '1.0.0',
		register(_ctx: PluginContext): PluginRegistration {
			type SdkEnv = {
				Bindings: { DB: D1Database; ADMIN_PASSWORD: string };
				Variables: { auth: import('@/lib/services/auth.service').AuthContext };
			};
			const app = new Hono<SdkEnv>();
			app.use('*', requireAuth);
			app.use('*', requireAdmin); // Schema disclosure requires admin

			// Auto-generate SDK
			app.get('/types', async (c) => {
				const db = new D1Client((c.env as Record<string, unknown>).DB as D1Database);
				const collections = await findAllCollections(db);
				const types = generateTypes(collections);
				return c.newResponse(types, 200, { 'Content-Type': 'text/plain' });
			});

			// Minimal SDK code (copy-paste into frontend)
			app.get('/generate', async (c) => {
				const db = new D1Client((c.env as Record<string, unknown>).DB as D1Database);
				const collections = await findAllCollections(db);
				const sdk = [
					'// Copy this into your frontend project',
					`const baseUrl = '${new URL(c.req.url).origin}'`,
					generateTypes(collections),
				].join('\n');
				return c.newResponse(sdk, 200, { 'Content-Type': 'text/plain' });
			});

			return { routes: [{ path: '/api/sdk', handler: app as unknown as Hono }] };
		},
	};
}
