// Auto-generates packages/design-system/src/index.ts from the component
// directories in src/ — so exports can never silently go missing again.
//
// Usage:
//   node scripts/exports.mjs            # write src/index.ts
//   node scripts/exports.mjs --check    # verify src/index.ts is in sync (CI)
import { readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const srcDir = path.resolve(__dirname, "../src")
const componentsDir = path.join(srcDir, "components")
const indexFile = path.join(srcDir, "index.ts")

// Directories that are NOT components (docs, tokens, libs).
const SKIP = new Set(["foundations", "docs", "hooks", "types", "utils"])

// Heavy components — subpath imports only (@mmbix/design-system/chart, etc.)
// so the core bundle stays lean for edge runtimes. `widgets` is subpath-only
// too: the Scheduler widget (~1k lines) must never land in the core index.js.
const SUBPATH_ONLY = new Set([
  "datatable",
  "kanban",
  "calendar",
  "datepicker",
  "command",
  "carousel",
  "scheduler",
  "widgets",
  "rich-text-editor",
])

// Sidebar's exports are listed explicitly so the canonical `SidebarHeader`
// (from ./sidebar) wins over appshell's same-named export.
const SIDEBAR_EXPORTS = [
  "Sidebar",
  "SidebarContent",
  "SidebarFooter",
  "SidebarGroup",
  "SidebarGroupAction",
  "SidebarGroupContent",
  "SidebarGroupLabel",
  "SidebarHeader",
  "SidebarInput",
  "SidebarInset",
  "SidebarMenu",
  "SidebarMenuAction",
  "SidebarMenuBadge",
  "SidebarMenuButton",
  "SidebarMenuItem",
  "SidebarMenuSkeleton",
  "SidebarMenuSub",
  "SidebarMenuSubButton",
  "SidebarMenuSubItem",
  "SidebarProvider",
  "SidebarRail",
  "SidebarSeparator",
  "SidebarTrigger",
  "useSidebar",
]

const AUTO_GEN_NOTICE =
  "// NOTE: This file is auto-generated by scripts/exports.mjs.\n" +
  "// Run `pnpm generate:exports` after adding or removing a component.\n" +
  `// Heavy components (${[...SUBPATH_ONLY].join(", ")}) are exported via\n` +
  "// subpath imports only to keep the core bundle lean for edge runtimes.\n"

function componentDirs() {
  return readdirSync(componentsDir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .filter((name) => !SKIP.has(name) && !SUBPATH_ONLY.has(name))
    .filter((name) =>
      ["index.tsx", "index.ts"].some((file) =>
        existsSync(path.join(componentsDir, name, file))
      )
    )
    .sort()
}

function generate() {
  const components = componentDirs()
  const lines = [
    AUTO_GEN_NOTICE,
    "// CSS — imported here so Vite bundles it into dist/index.css",
    'import "./index.css"',
    "",
    'export { ThemeProvider, useTheme } from "./components/theme-provider"',
    'export { cn } from "./lib/utils"',
    'export { lockBodyScroll, unlockBodyScroll, useScrollLock } from "./lib/hooks/use-scroll-lock"',
    "",
  ]

  for (const name of components) {
    if (name === "sidebar") continue
    lines.push(`export * from "./components/${name}"`)
  }

  lines.push("")
  lines.push(
    "// NOTE: Sidebar's exports are listed explicitly below so the canonical"
  )
  lines.push(
    "// `SidebarHeader` (from ./sidebar) wins over appshell's same-named export."
  )
  lines.push("export {")
  for (const exp of SIDEBAR_EXPORTS) {
    lines.push(`  ${exp},`)
  }
  lines.push('} from "./components/sidebar"')
  lines.push("")

  return lines.join("\n")
}

function main() {
  const check = process.argv.includes("--check")
  const generated = generate()
  const target = indexFile

  if (check) {
    const current = readFileSync(target, "utf-8")
    if (current === generated) {
      console.log(
        `[exports] ✓ ${target} is in sync (${componentDirs().length} components)`
      )
      return
    }
    console.error(
      "[exports] ✗ src/index.ts is out of sync with the component directories."
    )
    console.error("Run `pnpm generate:exports` to regenerate it.")
    process.exit(1)
  }

  writeFileSync(target, generated)
  console.log(
    `[exports] ✓ regenerated ${target} (${componentDirs().length} components exported)`
  )
}

main()
