// Auto-generates packages/design-system/src/components/widgets/index.ts from
// the widget files in the same directory — one widget = one file, registered
// by its `widgetMeta` export. So a saved widget file is picked up by the
// palette + runtime without touching the registry by hand.
//
// Usage:
//   node scripts/widgets.mjs             # write src/components/widgets/index.ts
//   node scripts/widgets.mjs --check     # verify it's in sync (CI)
import { readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const widgetsDir = path.resolve(__dirname, "../src/components/widgets")
const indexFile = path.join(widgetsDir, "index.ts")

const NOTICE =
  "// NOTE: This file is auto-generated by scripts/widgets.mjs.\n" +
  "// Run `node scripts/widgets.mjs` after adding or removing a widget file."

function widgetFiles() {
  return readdirSync(widgetsDir)
    .filter((f) => f.endsWith(".tsx") && f !== "index.tsx")
    .filter((f) => f !== "types.ts")
    .sort()
}

function camel(name) {
  return name.replace(/-([a-z])/g, (_, c) => c.toUpperCase())
}

function generate() {
  const files = widgetFiles()
  const imports = files.map((f) => {
    const name = f.replace(/\.tsx$/, "")
    const src = readFileSync(path.join(widgetsDir, f), "utf-8")
    const exportName = src.match(/export\s+function\s+(\w+)/)?.[1]
    if (!exportName) throw new Error(`widget ${name}: missing \`export function Xxx\` component`)
    return { name, exportName }
  })
  const lines = [
    NOTICE,
    'import type { WidgetDef } from "./types"',
    ...imports.map((w) => `import { ${w.exportName}, widgetMeta as ${camel(w.name)}Meta } from "./${w.name}"`),
    "",
    "export const WIDGET_REGISTRY: WidgetDef[] = [",
    ...imports.map((w) => `  ${camel(w.name)}Meta,`),
    "]",
    "",
    ...imports.map((w) => `export { ${w.exportName} } from "./${w.name}"`),
    "",
    "export function widgetDefOf(type: string): WidgetDef | undefined {",
    "\treturn WIDGET_REGISTRY.find((w) => w.type === type)",
    "}",
    "",
    "/** Default config for a new widget block (spread into `config` on insert). */",
    "export function widgetDefaults(def: WidgetDef): Record<string, unknown> {",
    "\tconst out: Record<string, unknown> = { ...def.defaultProps }",
    "\t// Merge `props[*].default` values that defaultProps doesn't already set —",
    "\t// so a dropped widget gets its real field-mapping defaults (e.g.",
    "\t// employee-card nameField: 'full_name'), not an empty config.",
    "\tfor (const [key, prop] of Object.entries(def.props)) {",
    "\t\tif (out[key] === undefined && prop.default !== undefined) out[key] = prop.default",
    "\t}",
    "\treturn out",
    "}",
    "",
    	'export type { WidgetDef, WidgetPropDef, WidgetPropType } from "./types"',
    "",
  ]
  return lines.join("\n")
}

function main() {
  const check = process.argv.includes("--check")
  const generated = generate()
  if (check) {
    if (existsSync(indexFile) && readFileSync(indexFile, "utf-8") === generated) {
      console.log(`[widgets] ✓ ${indexFile} is in sync (${widgetFiles().length} widgets)`)
      return
    }
    console.error("[widgets] ✗ index.ts is out of sync with the widget files.")
    console.error("Run `node scripts/widgets.mjs` to regenerate it.")
    process.exit(1)
  }
  writeFileSync(indexFile, generated)
  console.log(`[widgets] ✓ regenerated ${indexFile} (${widgetFiles().length} widgets)`)
}

main()
