import { cloneElement } from 'react';
import {
	AlignLeft,
	Braces,
	Calendar,
	CalendarClock,
	CheckSquare,
	CircleDollarSign,
	Clock,
	Clock4,
	Code,
	FileSpreadsheet,
	FileText,
	Fingerprint,
	FunctionSquare,
	Gauge,
	Globe,
	Hash,
	ImageIcon,
	Layers,
	Link,
	Link2,
	ListFilter,
	ListTree,
	Lock,
	Mail,
	MapPin,
	Palette,
	Paperclip,
	PenLine,
	Percent,
	Phone,
	ScanBarcode,
	Sparkles,
	Star,
	Table2,
	Tags,
	Timer,
	Type,
} from 'lucide-react';

/** Colored icon per field type (Directus-style field preview) — shared by the layout editor and collection views. */
export function FieldTypeIcon({ type, size = 13 }: { type: string; size?: number }) {
	const map: Record<string, { el: React.ReactElement<{ size?: number }>; color: string }> = {
		text: { el: <Type />, color: '#2563eb' },
		longtext: { el: <AlignLeft />, color: '#7c3aed' },
		text_editor: { el: <FileText />, color: '#7c3aed' },
		markdown: { el: <FileText />, color: '#7c3aed' },
		code: { el: <Code />, color: '#7c3aed' },
		email: { el: <Mail />, color: '#2563eb' },
		url: { el: <Globe />, color: '#2563eb' },
		phone: { el: <Phone />, color: '#0891b2' },
		password: { el: <Lock />, color: '#4b5563' },
		slug: { el: <Link />, color: '#0891b2' },
		uuid: { el: <Fingerprint />, color: '#4b5563' },
		json: { el: <Braces />, color: '#4b5563' },
		csv: { el: <FileSpreadsheet />, color: '#16a34a' },
		integer: { el: <Hash />, color: '#dc2626' },
		bigint: { el: <Hash />, color: '#dc2626' },
		number: { el: <Hash />, color: '#dc2626' },
		currency: { el: <CircleDollarSign />, color: '#16a34a' },
		percent: { el: <Percent />, color: '#16a34a' },
		rating: { el: <Star />, color: '#f59e0b' },
		progress: { el: <Gauge />, color: '#16a34a' },
		duration: { el: <Timer />, color: '#0891b2' },
		formula: { el: <FunctionSquare />, color: '#7c3aed' },
		boolean: { el: <CheckSquare />, color: '#16a34a' },
		select: { el: <ListFilter />, color: '#ea580c' },
		tags: { el: <Tags />, color: '#ea580c' },
		color: { el: <Palette />, color: '#ec4899' },
		icon: { el: <Sparkles />, color: '#ec4899' },
		datetime: { el: <CalendarClock />, color: '#0891b2' },
		date: { el: <Calendar />, color: '#0891b2' },
		time: { el: <Clock />, color: '#0891b2' },
		timestamp: { el: <Clock4 />, color: '#0891b2' },
		file: { el: <Paperclip />, color: '#4b5563' },
		signature: { el: <PenLine />, color: '#4b5563' },
		barcode: { el: <ScanBarcode />, color: '#4b5563' },
		location: { el: <MapPin />, color: '#16a34a' },
		image: { el: <ImageIcon />, color: '#7c3aed' },
		m2o: { el: <Link2 />, color: '#2563eb' },
		o2m: { el: <ListTree />, color: '#2563eb' },
		m2m: { el: <Link2 />, color: '#2563eb' },
		m2a: { el: <Layers />, color: '#2563eb' },
		table: { el: <Table2 />, color: '#2563eb' },
	};
	const hit = map[type];
	if (!hit)
		return <span style={{ width: size, height: size, borderRadius: 3, background: '#e5e7eb', display: 'inline-block', flexShrink: 0 }} />;
	return <span style={{ color: hit.color, display: 'inline-flex', flexShrink: 0 }}>{cloneElement(hit.el, { size })}</span>;
}
