// AUTO-GENERATED by @mmbix/sdk typegen (--target dart) — DO NOT EDIT.
// source-hash: 5868b06a1b11480d1fb9dec08dccf7845dbbc3a3b4798254d37096f38e53520e
//
// Row models for the entity schema — one plain-Dart class per collection
// (fromJson/toJson, no build_runner), field-name constants for the F.* filter
// factories, and the canonical API error codes this deployment emits.
// Re-run the generator after any schema change; everything updates together.

// ── Row models ─────────────────────────────────────────────

/// Row model for the `contacts` collection.
class Contacts {
	const Contacts({
		required this.id,
		this.fullName,
		this.email,
		this.phone,
	});

	final String id;
	final String? fullName;
	final String? email;
	final String? phone;

	factory Contacts.fromJson(Map<String, Object?> json) => Contacts(
		id: json['id'] as String,
		fullName: json['full_name'] as String?,
		email: json['email'] as String?,
		phone: json['phone'] as String?,
	);

	/// PATCH-style payload — null fields are OMITTED (absent ≠ explicit
	/// null), so a round-tripped row never silently clears a column.
	Map<String, Object?> toJson() => {
		'id': id,
		if (fullName != null) 'full_name': fullName,
		if (email != null) 'email': email,
		if (phone != null) 'phone': phone,
	};
}

/// Row model for the `work_orders` collection.
class WorkOrders {
	const WorkOrders({
		required this.id,
		this.code,
		this.title,
		this.status,
		this.priority,
		this.isBillable,
		this.rate,
		this.metaNote,
		this.assignedTo,
		this.total,
		this.isOverdue,
		this.createdAt,
		this.updatedAt,
	});

	final String id;
	final String? code;
	final String? title;
	final String? status;
	final num? priority;
	final bool? isBillable;
	final num? rate;
	final String? metaNote;
	final String? assignedTo;
	final num? total;
	final bool? isOverdue;
	final String? createdAt;
	final String? updatedAt;

	factory WorkOrders.fromJson(Map<String, Object?> json) => WorkOrders(
		id: json['id'] as String,
		code: json['code'] as String?,
		title: json['title'] as String?,
		status: json['status'] as String?,
		priority: json['priority'] as num?,
		isBillable: _dbBool(json['is_billable']),
		rate: json['rate'] as num?,
		metaNote: json['meta_note'] as String?,
		assignedTo: json['assigned_to'] as String?,
		total: json['total'] as num?,
		isOverdue: _dbBool(json['is_overdue']),
		createdAt: json['created_at'] as String?,
		updatedAt: json['updated_at'] as String?,
	);

	/// PATCH-style payload — null fields are OMITTED (absent ≠ explicit
	/// null), so a round-tripped row never silently clears a column.
	Map<String, Object?> toJson() => {
		'id': id,
		if (code != null) 'code': code,
		if (title != null) 'title': title,
		if (status != null) 'status': status,
		if (priority != null) 'priority': priority,
		if (isBillable != null) 'is_billable': isBillable,
		if (rate != null) 'rate': rate,
		if (metaNote != null) 'meta_note': metaNote,
		if (assignedTo != null) 'assigned_to': assignedTo,
		if (total != null) 'total': total,
		if (isOverdue != null) 'is_overdue': isOverdue,
		if (createdAt != null) 'created_at': createdAt,
		if (updatedAt != null) 'updated_at': updatedAt,
	};
}

// ── Field constants (F.* factories) ────────────────────────

/// Field-name constants for the `contacts` collection — pass them to
/// the `F.*` filter factories (`F.eq(ContactsFields.fullName, …)`); a misspelled
/// field is a compile error.
abstract final class ContactsFields {
	static const id = 'id';
	static const fullName = 'full_name';
	static const email = 'email';
	static const phone = 'phone';
}

/// Field-name constants for the `work_orders` collection — pass them to
/// the `F.*` filter factories (`F.eq(WorkOrdersFields.code, …)`); a misspelled
/// field is a compile error.
abstract final class WorkOrdersFields {
	static const id = 'id';
	static const code = 'code';
	static const title = 'title';
	static const status = 'status';
	static const priority = 'priority';
	static const isBillable = 'is_billable';
	static const rate = 'rate';
	static const metaNote = 'meta_note';
	static const assignedTo = 'assigned_to';
	static const total = 'total';
	static const isOverdue = 'is_overdue';
	static const createdAt = 'created_at';
	static const updatedAt = 'updated_at';
}

// ── Canonical API error codes ──────────────────────────────

/// Canonical API error codes this deployment emits — `GET /api/meta` →
/// `error_codes`. Compare against `ErpHttpException.apiCode`.
abstract final class ApiErrorCodes {
	static const validationError = 'VALIDATION_ERROR';
	static const invalidJson = 'INVALID_JSON';
	static const unauthorized = 'UNAUTHORIZED';
	static const forbidden = 'FORBIDDEN';
	static const notFound = 'NOT_FOUND';
	static const conflict = 'CONFLICT';
	static const payloadTooLarge = 'PAYLOAD_TOO_LARGE';
	static const unsupportedMediaType = 'UNSUPPORTED_MEDIA_TYPE';
	static const rateLimitExceeded = 'RATE_LIMIT_EXCEEDED';
	static const notConfigured = 'NOT_CONFIGURED';
	static const databaseError = 'DATABASE_ERROR';
	static const internalError = 'INTERNAL_ERROR';

	/// Every code, in catalog order.
	static const List<String> all = [
		validationError,
		invalidJson,
		unauthorized,
		forbidden,
		notFound,
		conflict,
		payloadTooLarge,
		unsupportedMediaType,
		rateLimitExceeded,
		notConfigured,
		databaseError,
		internalError,
	];
}

// ── Internals ──────────────────────────────────────────────

/// D1 stores booleans as INTEGER 0/1 (JSON `number`) — normalize to `bool`.
bool? _dbBool(Object? value) {
	if (value is bool) return value;
	if (value is num) return value != 0;
	return null;
}
